basicapp/urls.py
from django.urls import path
from basicapp import views

app_name='basicapp'

urlpatterns = [
    path('register/',views.register,name='register')

]

learnuser/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
from learnuser import settings

from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.DO_NOTHING,)

    #additional

    portfolio_site=models.URLField(blank=True)


    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)



    def __str__(self):
        return self.user.username
    

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model =User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo 
        fields = ('portfolio_site','profile_pic')  

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserProfileInfoForm,UserForm

# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')

def register(request):

    registered =False

    if request.method =="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user =user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user= user

            if 'profile_pic'in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered=True
        
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basicapp/registeration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})            

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
</head>
<body>

        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                <!-- Brand -->

                <a class="navbar-brand" href="{% url 'index' %}">Navbar</a>
              
                <!-- Toggler/collapsibe Button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <!-- Navbar links -->
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'basicapp:register' %}">Link</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Link</a>
                    </li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                      </ul>
                    </div>
                </nav> 
    
              <div class="container">
                    {% block body_block %}
                    {% endblock%}

              </div>
</body>
</html>

templates/basicapp/index.html
{% extends "basicapp/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>WE are at level 5</h1>
    
</div>

{% endblock %}

templates/basicapp/registeration.html
{% extends 'basicapp/base.html'%}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">

    {%if registered %}

    <h1>Thank you for registering !</h1>

    {% else %}
        <h1> Register Here !</h1>
        <h3>Fill out the form : </h3>

        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>

    {% endif %}

</div>
{% endblock %}